M48
; DRILL file {KiCad 7.0.1-0} date 2024 August 11, Sunday 08:49:19
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-11T08:49:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.3228Y-2.6969
X2.3228Y-4.0748
X5.0591Y-3.3465
X6.9488Y-3.3465
T0
M30
